name: Projeto Tech-Challenge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag techchallenge:latest
      - name: permission to run testes
        run: chmod +x ./src/tests/api.test.js
      - name: Run tests
        run: docker run --rm techchallenge:latest npm test
